server:
  port: 9092

eureka:
  client:
    fetch-service-url:
      defaultZone: http://localhost:8761/

spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver